version: '2'
services:

  mariadb:
    image: mariadb
    env_file:
      - .env
    volumes:
      - './data/mariadb:/var/lib/mysql'

  phpbb:
    build: phpbb
    env_file:
      - .env
    environment:
      - DBHOST=mariadb
      - DBPORT=3306
      - DBNAME=${MYSQL_DATABASE}
      - DBUSER=${MYSQL_USER}
      - DBPASSWD=${MYSQL_PASSWORD}
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './data/phpbb/files:/var/www/html/files'
      - './data/phpbb/store:/var/www/html/store'
      - './data/phpbb/avatars:/var/www/html/images/avatars/upload'
    depends_on:
      - mariadb
