version: '2'
services:

  mariadb:
    image: mariadb
    env_file:
      - .env
    volumes:
      - './data/mariadb:/var/lib/mysql'

  phpbb:
    image: 'bitnami/phpbb:3'
    env_file:
      - .env
    environment:
      - PHPBB_PASSWORD=${PHPBB_PASSWORD}
      - PHPBB_DATABASE_USER=${MYSQL_USER}
      - PHPBB_DATABASE_NAME=${MYSQL_DATABASE}
      - PHPBB_DATABASE_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './data/phpbb:/bitnami'
    depends_on:
      - mariadb
